### ISSUE TITLE
Compilation error on non ubuntu based distros

### ISSUE THREAD

**Issue by PrimeO7** [gwolf-011235/minishell#80]
Upstream readline does not include stdio.h.

Only reason it works on Ubuntu/Debian is because they patch it in (btw, this is considered bad practice).
This will cause compilation errors on Linux distributions that stay closer to upstream.

The [manpage](https://man7.org/linux/man-pages/man3/readline.3.html) even states that you should include stdio.h first
